import localFont from 'next/font/local';

import { FavoritesProvider } from '@/features/product/favorites-provider';
import QueryProvider from '@/shared/lib/query-provider';
import { SessionProvider } from '@/shared/lib/session-provider';
import { Header } from '@/widgets';

import type { Metadata } from 'next';

import '../shared/styles/index.scss';

const roboto = localFont({
  src: [
    {
      path: '../shared/assets/fonts/Roboto-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../shared/assets/fonts/Roboto-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../shared/assets/fonts/Roboto-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-roboto',
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={roboto.className}>
        <QueryProvider>
          <FavoritesProvider>
            <SessionProvider />
            <Header />
            <main className={'container'}>{children}</main>
          </FavoritesProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
